"""Initial transaction event tables

Revision ID: 415f3a9f0b4b
Revises: 
Create Date: 2025-10-05 06:35:46.312847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '415f3a9f0b4b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('wallet_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=19, scale=4), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('transaction_id', sa.String(length=36), nullable=False),
    sa.Column('event_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    op.create_index('idx_transaction_event_transaction_id', 'transaction_events', ['transaction_id'], unique=False)
    op.create_index('idx_transaction_event_user_id', 'transaction_events', ['user_id'], unique=False)
    op.create_index('idx_transaction_event_wallet_id', 'transaction_events', ['wallet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_transaction_event_wallet_id', table_name='transaction_events')
    op.drop_index('idx_transaction_event_user_id', table_name='transaction_events')
    op.drop_index('idx_transaction_event_transaction_id', table_name='transaction_events')
    op.drop_table('transaction_events')
    # ### end Alembic commands ###
