"""Increade character length for transaction_id

Revision ID: f099a09999ff
Revises: 415f3a9f0b4b
Create Date: 2025-10-05 21:16:41.435775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f099a09999ff'
down_revision: Union[str, Sequence[str], None] = '415f3a9f0b4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transaction_events', 'transaction_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=150),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transaction_events', 'transaction_id',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    # ### end Alembic commands ###
