"""create wallets and wallet_transactions tables

Revision ID: 53b8d0b28712
Revises: c8d57d9bb04d
Create Date: 2025-10-29 14:04:14.734330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53b8d0b28712'
down_revision: Union[str, Sequence[str], None] = 'c8d57d9bb04d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
